spring:
  application:
    name: ${SPRING.APP.NAME:user-management}
  banner:
    location: ${SPRING.BANNER:classpath:/banners/banner.txt}

server:
  port: ${SERVER.PORT:9095}

# ===============================
# = SPRING DATABASE
# ===============================
datasource:
  driverClassName: ${DATASOURCE.DRIVER.NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  databaseUrl: ${DATASOURCE.DATABASE.URL:jdbc:sqlserver://localhost;DatabaseName=friend-finder;characterEncoding=UTF-8;encrypt=false}
  databaseUser: ${DATASOURCE.USER.NAME:sasa}
  databasePassword: ${DATASOURCE.USER.PASSWORD:sasasasa}
  platform: ${DATASOURCE.PLATFORM:org.hibernate.dialect.SQLServer2012Dialect}

# ===============================
# = JPA / HIBERNATE
# ===============================
jpa:
  showSql: ${JPA.SHOW_SQL:true}
  hibernate:
    hibernateDDLAuto: ${JPA.HIBERNATE.DDL.AUTO:none}
    hibernateDialect: ${JPA.HIBERNATE.DIALECT:org.hibernate.dialect.SQLServer2012Dialect}
    create_empty_composites:
      enabled: ${JPA.HIBERNATE.EMPTY.COMPOSITES:true}

