spring:
  application:
    name: user-management
  banner:
    location: classpath:/banners/banner.txt

server:
  port: 9095

# ===============================
# = SPRING DATABASE
# ===============================
datasource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  databaseUrl: jdbc:sqlserver://localhost;DatabaseName=friend-finder;characterEncoding=UTF-8;encrypt=false
  databaseUser: sasa
  databasePassword: sasasasa
  platform: org.hibernate.dialect.SQLServer2012Dialect

# ===============================
# = JPA / HIBERNATE
# ===============================
jpa:
  showSql:  true
  hibernate:
    hibernateDDLAuto:  none
    hibernateDialect:  org.hibernate.dialect.SQLServer2012Dialect
    create_empty_composites:
        enabled: true

